# Generated by Django 4.2.7 on 2026-02-11 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('PHARMACY', 'Pharmacy'), ('CONSUMER', 'Consumer')], max_length=20)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('city', models.CharField(default='Lahore', max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity_manufactured', models.PositiveIntegerField()),
                ('unit_type', models.CharField(choices=[('Box', 'Box'), ('Bottle', 'Bottle'), ('Strip', 'Strip')], max_length=20)),
                ('manufacturing_site', models.CharField(max_length=255)),
                ('quality_certification_code', models.CharField(max_length=100)),
                ('storage_conditions', models.TextField()),
                ('mrp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribution_region', models.CharField(max_length=255)),
                ('batch_status', models.CharField(choices=[('CREATED', 'Created'), ('DISTRIBUTED', 'Distributed'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled')], default='CREATED', max_length=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_status', models.CharField(choices=[('NOT_REGISTERED', 'Not Registered'), ('PENDING', 'Pending'), ('REGISTERED', 'Registered')], default='NOT_REGISTERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('drug_license_number', models.CharField(max_length=100, unique=True)),
                ('manufacturing_address', models.TextField()),
                ('city', models.CharField(default='Lahore', max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_manufacturers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_value', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='api.batch')),
            ],
            options={
                'db_table': 'qr_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('dosage_form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection')], max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.manufacturer')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_name'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.product'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'batch_number')},
        ),
    ]
