# Generated by Django 4.2.7 on 2026-05-09 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pharmacy_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='api.batch')),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_sent', to=settings.AUTH_USER_MODEL)),
                ('dispatched_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_dispatches',
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
