# Generated by Django 4.2.7 on 2026-05-12 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_batchdispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensedQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='api.batch')),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_qrs', to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_records', to='api.qrcode')),
            ],
            options={
                'db_table': 'dispensed_qrs',
                'ordering': ['-dispensed_at'],
                'unique_together': {('qr_code', 'dispensed_by')},
            },
        ),
    ]
